### PR TITLE
Creole

### PR DESCRIPTION
**Pull request by lucaskanashiro**
Add Creole markup language support

### CODE REVIEW

**Comment by theory** [comment]
And v0.22 is on its way to CPAN with this change. Thanks @lucaskanashiro!

**Comment by lucaskanashiro** [comment]
Nice @theory!

**Comment by lucaskanashiro** [comment]
@theory you forgot to update the description in CPAN, add the news markup languages ;-)

**Comment by theory** [comment]
What? Where?

**Comment by lucaskanashiro** [comment]
In this description: http://search.cpan.org/~dwheeler/Text-Markup-0.22/lib/Text/Markup.pm

**Comment by theory** [comment]
Oh. Would you add them and submit a PR?

**Comment by lucaskanashiro** [comment]
OK

**Pull request merged**
