### PR TITLE
Add BBcode support

### PR DESCRIPTION
**Pull request by lucaskanashiro**
Added BBcode support in Text::Markup

### CODE REVIEW

**Comment by theory** [comment]
I think you need to add `Parse::BBCode` to `Build.PL`.

**Comment by theory** [comment]
Also need to fix the Pod error (see Travis failures).

**Comment by theory** [comment]
One more thing: I think the filename suffix [should be .bb](http://filext.com/file-extension/BB).

**Comment by theory** [comment]
Or maybe both `.bb` and `.bbcode`.

**Comment by lucaskanashiro** [comment]
Done @theory

**Comment by theory** [comment]
Thanks!

**Pull request merged**
