### PR TITLE
Use warnings and fix spelling test

### PR DESCRIPTION
**Pull request by lucaskanashiro**
- Added 'use warnings' in all Perl files
- Fix a POD spelling test

### CODE REVIEW

**Comment by theory** [comment]
I see no need for this.

**Comment by lucaskanashiro** [comment]
No need for the addition of 'use warnings'? Or the spelling test? 
With warnings I tried to make a little improvement based in one CPAN extra metric (http://cpants.cpanauthors.org/dist/Text-Markup), are you think that it's not necessary?
I executed the suite test and the POD spelling test are failing here, I only added another stop word to pass it.

**Comment by theory** [comment]
The spelling fix is fine, but there is no need for `use warnings;` in the code. It can be nice to have when doing diagnostics, but isn't necessary in shipping code, IMO, especially since warnings are enabled in the tests.

**Comment by lucaskanashiro** [comment]
OK @theory ! I will reset the 'use warnings;' commit and leave only the spelling fix.

**Comment by lucaskanashiro** [comment]
Done.

**Pull request merged**
